version: 2

jobs:
  test:
    docker:
      image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip install tox
      - run:
          name: Run tox
          command: |
            tox

workflows:
  test-build-deploy:
    - test
